       <div class="titrePage" style="margin-bottom: 45px;">
          <div><h3>Liste des livres</h3></div>
        </div>  
          
      <div class="row">
        <div class="col-md-10 col-md-offset-1">        
          <table class="table table-bordered table-striped table-responsive colBack">
            <thead>
              <tr>
                <th>ISBN</th>
                <th>Titre</th>
                <th>Type</th>
                <th>Catégorie</th>
                <th>Etat</th>
                <th>Editeur</th>
                <th>Format</th>
                <th>Année</th>
                <th>Auteur</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1234567789</td>
                <td>Maths pour les Nuls</td>
                <td></td>
                <td></td>
                <td>Neuf</td>
                <td></td>
                <td></td>
                <td>2010</td>
                <td></td>
              </tr>
              <tr>
                <td>1476567898</td>
                <td>Science simple</td>
                <td></td>
                <td></td>
                <td>Bon</td>
                <td></td>
                <td></td>
                <td>2014</td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table> 
				</div>
      </div>